In [78]:
import numpy as np

In [79]:
# Array Generation

In [80]:
arr = np.array([1,2,3,4,5,6,7])

In [81]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [82]:
l = [[1,2,3,4] , [5,6,7,8]]

In [83]:
l # Python list show in vector only

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [84]:
arr = np.array(l) # Numpy array show data in matrix and can be show in 2 dimension and in tensors

In [85]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:
l = [1,2,3.4,"Musa"]

In [87]:
l

[1, 2, 3.4, 'Musa']

In [88]:
arr = np.array(l) # Numpy array contain only single data type

In [89]:
arr

array(['1', '2', '3.4', 'Musa'], dtype='<U32')

In [90]:
# Array Generation functions

In [91]:
np.zeros((6,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [92]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [93]:
np.linspace(1,10,2)

array([ 1., 10.])

In [94]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [95]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [96]:
# Random Array Generation

In [97]:
np.random.rand(10) # Normalization 0 to 1

array([0.35180489, 0.47947785, 0.92405062, 0.6507247 , 0.2729099 ,
       0.78220945, 0.74448115, 0.60918679, 0.36864247, 0.3012689 ])

In [98]:
np.random.randn(6) # Standarization -3 to +3

array([-0.48158652,  0.02349596, -0.19133646, -0.15590924,  1.29728856,
       -0.32255487])

In [99]:
np.random.randint(10,20,5) # Any random number between specifice range

array([16, 18, 19, 11, 17])

In [100]:
# Array Attributes

In [101]:
arr = np.array([[1,2,3,4] , [5,6,7,8]])

In [102]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [103]:
arr.shape

(2, 4)

In [104]:
arr.size

8

In [105]:
arr.dtype

dtype('int64')

In [106]:
arr.dump

<function ndarray.dump>

In [107]:
# Array method

In [108]:
arr.min()

np.int64(1)

In [109]:
arr.max()

np.int64(8)

In [110]:
arr.argmin()

np.int64(0)

In [111]:
arr.argmax()

np.int64(7)

In [112]:
arr.mean()

np.float64(4.5)

In [113]:
arr.std()

np.float64(2.29128784747792)

In [114]:
# Reshaping and resizing

In [115]:
arr = np.arange(1,31)

In [116]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [120]:
arr = np.arange(1,31)
arr = arr.reshape(6,5)

In [121]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [122]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])