In [97]:
import numpy as np

In [98]:
# Array Operation

In [99]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [100]:
a + b

array([ 6,  8, 10, 12])

In [101]:
a - b

array([-4, -4, -4, -4])

In [102]:
a * b

array([ 5, 12, 21, 32])

In [103]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [104]:
a // b

array([0, 0, 0, 0])

In [105]:
a ** b

array([    1,    64,  2187, 65536])

In [106]:
# Broadcasting

In [107]:
a

array([1, 2, 3, 4])

In [108]:
a + 10

array([11, 12, 13, 14])

In [109]:
a ** 10

array([      1,    1024,   59049, 1048576])

In [110]:
# Deep Copy

In [111]:
B = a.copy()
B[0] = 1
B

array([1, 2, 3, 4])

In [112]:
a

array([1, 2, 3, 4])

In [113]:
# Shallow copy

In [114]:
a

array([1, 2, 3, 4])

In [115]:
B = a
B[0] = 99

In [116]:
B

array([99,  2,  3,  4])

In [117]:
a

array([99,  2,  3,  4])

In [118]:
a

array([99,  2,  3,  4])

In [119]:
# Matrix operation

In [120]:
a = np.arange(1,31).reshape(6,5)

In [121]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [122]:
b = np.arange(1,31).reshape(5,6)

In [123]:
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [124]:
a @ b

array([[ 255,  270,  285,  300,  315,  330],
       [ 580,  620,  660,  700,  740,  780],
       [ 905,  970, 1035, 1100, 1165, 1230],
       [1230, 1320, 1410, 1500, 1590, 1680],
       [1555, 1670, 1785, 1900, 2015, 2130],
       [1880, 2020, 2160, 2300, 2440, 2580]])

In [125]:
np.dot(a,b)

array([[ 255,  270,  285,  300,  315,  330],
       [ 580,  620,  660,  700,  740,  780],
       [ 905,  970, 1035, 1100, 1165, 1230],
       [1230, 1320, 1410, 1500, 1590, 1680],
       [1555, 1670, 1785, 1900, 2015, 2130],
       [1880, 2020, 2160, 2300, 2440, 2580]])

In [126]:
# Stacking

In [127]:
a = np.arange(1,11).reshape(2,5)
b = np.arange(11,21).reshape(2,5)

In [128]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [129]:
b

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [130]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [131]:
np.hstack((a,b))

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [132]:
np.column_stack((a,b))

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [133]:
# Spliting

In [134]:
np.vsplit(a,2)

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]

In [135]:
np.hsplit(a,1)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])]