In [1]:
import numpy as np

In [3]:
# Array indexing and slicing of vector

In [4]:
arr = np.arange(10,21)

In [5]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[1]

np.int64(11)

In [7]:
arr[3]

np.int64(13)

In [8]:
arr[7]

np.int64(17)

In [9]:
arr[0:3]

array([10, 11, 12])

In [10]:
arr[2:6]

array([12, 13, 14, 15])

In [11]:
arr[::2]

array([10, 12, 14, 16, 18, 20])

In [12]:
arr[1::2]

array([11, 13, 15, 17, 19])

In [16]:
# Array indexing and slicing of matrix

In [17]:
arr = np.arange(1,31).reshape(6,5)

In [18]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [19]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [20]:
arr[0]

array([1, 2, 3, 4, 5])

In [21]:
arr[3]

array([16, 17, 18, 19, 20])

In [22]:
arr[0:2,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [24]:
arr[4:,2:]

array([[23, 24, 25],
       [28, 29, 30]])

In [25]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [26]:
# Boolean Inddexing

In [39]:
arr = np.arange(11,21)

In [40]:
bool_arr = arr % 2 ==0

In [41]:
bool_arr

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [42]:
arr = arr[bool_arr]

In [43]:
arr

array([12, 14, 16, 18, 20])

In [44]:
odd = arr % 2 != 0
arr = arr[odd]
arr

array([], dtype=int64)